name: recipe
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  go_router: ^14.3.0
  keyboard_dismisser: ^3.0.0
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  numberpicker: ^2.1.2
  cupertino_clock: ^1.0.0+1
  supabase_flutter: ^2.8.0
  flutter_bloc: ^8.1.6
  formz: ^0.8.0
  equatable: ^2.0.7
  crypto: ^3.0.6
  delightful_toast: ^1.1.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  device_info_plus: ^10.1.2
  pdfx: ^2.8.0
  epub_view: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  image_picker: ^1.1.2
  provider: ^6.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/pdfs/

  # https://flutter.dev/to/resolution-aware-images

  # https://flutter.dev/to/asset-from-package

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
